# Generated by Django 4.1.7 on 2023-03-26 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name': 'Меткa', 'verbose_name_plural': 'Метки'},
        ),
    ]
