# Generated by Django 4.1.7 on 2023-03-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0005_remove_task_labels_task_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(related_name='labels', to='labels.label'),
        ),
    ]
