# Generated by Django 4.1.7 on 2023-03-25 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=130)),
                ('creatad_at', models.DateTimeField(auto_now_add=True)),
                ('updatad_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 to=settings.AUTH_USER_MODEL, verbose_name='Владелец объявления')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuss',
            },
        ),
    ]
