# Generated by Django 4.1.7 on 2023-03-25 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='status_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='status',
            name='updatad_at',
        ),
        migrations.RemoveField(
            model_name='status',
            name='user',
        ),
    ]
