# Generated by Django 4.1.7 on 2023-03-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_rename_status_name_status_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='creatad_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=130, unique=True),
        ),
    ]
