# Generated by Django 4.1.7 on 2023-03-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0003_alter_status_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=130, unique=True, verbose_name='Имя'),
        ),
    ]
